export const PERMISSIONS = {
  BANK_DATA_VIEW: 'BANK_DATA_VIEW',
  BANK_DATA_PROCESS: 'BANK_DATA_PROCESS',

  CAMPAIGN_MANAGE: 'CAMPAIGN_MANAGE',
  FORM_MANAGE: 'FORM_MANAGE',

  LEAD_VIEW: 'LEAD_VIEW',
  /** Lead pipeline list (/lead-tracker); distinct from workspace tabs. */
  LEAD_TRACKER_VIEW: 'LEAD_TRACKER_VIEW',
  LEAD_MANAGE: 'LEAD_MANAGE',

  PROPOSAL_APPROVE: 'PROPOSAL_APPROVE',
  ENGAGEMENT_LETTER_APPROVE: 'ENGAGEMENT_LETTER_APPROVE',
  HANDOVER_APPROVE: 'HANDOVER_APPROVE',

  HANDOVER_MANAGE: 'HANDOVER_MANAGE',
  PROJECT_VIEW: 'PROJECT_VIEW',
  PROJECT_VIEW_FINANCIALS: 'PROJECT_VIEW_FINANCIALS',
  PROJECT_ASSIGN_PM: 'PROJECT_ASSIGN_PM',
  PROJECT_ASSIGN_CONSULTANT: 'PROJECT_ASSIGN_CONSULTANT',
  PROJECT_UPDATE_PROGRESS: 'PROJECT_UPDATE_PROGRESS',

  DOCUMENT_VIEW: 'DOCUMENT_VIEW',
  INVOICE_MANAGE: 'INVOICE_MANAGE',

  // KPI domain (Section 9.11 PRD)
  KPI_VIEW_OWN: 'KPI_VIEW_OWN',
  KPI_VIEW_TEAM: 'KPI_VIEW_TEAM',
  KPI_VIEW_ALL: 'KPI_VIEW_ALL',
  KPI_RATE_TASK: 'KPI_RATE_TASK',
  KPI_CONFIGURE: 'KPI_CONFIGURE',
  KPI_FINALIZE_PERIOD: 'KPI_FINALIZE_PERIOD',
  KPI_RECOMPUTE: 'KPI_RECOMPUTE',
  KPI_EXPORT: 'KPI_EXPORT',
  TASK_TEMPLATE_MANAGE: 'TASK_TEMPLATE_MANAGE'
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
